server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # NUEVO: Proxy para la API
    location /api/ {
        # 'api-container' es el nombre que le des al servicio en el pipeline/docker
        proxy_pass http://api-container:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /downloads/ {
        alias /usr/share/nginx/html/downloads/;
        add_header Content-Type application/vnd.android.package-archive;
    }
}
