sonar.host.url=http://localhost:9000
sonar.projectKey=proyecto-frontend
sonar.projectName=proyecto-frontend
# Dónde está el código
sonar.sources=src
# Excluir los tests del análisis de duplicaciones y bugs
sonar.exclusions=**/node_modules/**,**/*.spec.ts
# Si usas TypeScript, esto es vital
sonar.typescript.tsconfigPath=tsconfig.json
