sonar.host.url=http://localhost:9000
sonar.projectKey=proyecto-frontend
sonar.projectName=proyecto-frontend

# 1. Dónde está el código fuente real
sonar.sources=src
# Excluimos los archivos de test de la carpeta de fuentes
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# 2. Exclusiones de análisis (Bugs/Vulnerabilidades en fuentes)
# Aquí NO deben estar los .spec.ts
sonar.exclusions=**/node_modules/**, src/test-setup.ts

# 3. TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# 4. REPORTES DE VITEST (Vital para que Sonar "vea" los checks verdes)
# Asegúrate de haber configurado el reporter 'junit' en vitest.config.ts
sonar.junit.reportPaths=junit-report.xml
# Si vas a usar cobertura en el futuro:
sonar.javascript.lcov.reportPaths=coverage/lcov.info
